/**
 * Inlines Vite dashboard build output into a single HTML string
 * and writes it as a TypeScript module for tsup to bundle.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIST_DIR = join(import.meta.dirname, '..', 'dist', 'dashboard');
const OUT_FILE = join(import.meta.dirname, '..', 'src', 'dashboard-html.ts');

// Read the built index.html
let html = readFileSync(join(DIST_DIR, 'index.html'), 'utf-8');

// Find and inline CSS files
const assetsDir = join(DIST_DIR, 'assets');
try {
  const files = readdirSync(assetsDir);

  for (const file of files) {
    if (file.endsWith('.css')) {
      const css = readFileSync(join(assetsDir, file), 'utf-8');
      // Replace the <link> tag with inline <style>
      html = html.replace(
        new RegExp(`<link[^>]*href="[^"]*${file}"[^>]*>`),
        `<style>${css}</style>`,
      );
    }

    if (file.endsWith('.js')) {
      const js = readFileSync(join(assetsDir, file), 'utf-8');
      // Replace the <script> tag with inline script
      html = html.replace(
        new RegExp(`<script[^>]*src="[^"]*${file}"[^>]*></script>`),
        `<script type="module">${js}</script>`,
      );
    }
  }
} catch {
  // No assets dir means no CSS/JS to inline
}

// Write as a TS module
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
const output = `// Auto-generated by scripts/inline-assets.ts — do not edit\nexport const dashboardHtml = \`${escaped}\`;\n`;
writeFileSync(OUT_FILE, output);

console.log(`[inline-assets] Dashboard HTML inlined to ${OUT_FILE} (${html.length} bytes)`);
